name: "Build Project"

on:
  workflow_call:
    inputs:
      build-project:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        if: ${{ inputs.build-project == 'yes' }}
        uses: actions/checkout@v2

      - name: Project Workspace
        if: ${{ inputs.build-project == 'yes' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG
          echo ""
          cd $GITHUB_WORKSPACE
          echo "Working directory"
          pwd
          find .

      - name: Docker Images
        if: ${{ inputs.build-project == 'yes' }}
        run: |
          echo "Docker Images"
          echo ""
          docker images

      - name: Build Project
        if: ${{ inputs.build-project == 'yes' }}
        uses: ./.github/actions/build
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          environment: ${{ inputs.environment  }}

      - name: Skip project build
        if: ${{ inputs.build-project == 'no' }}
        run: echo "Skip project build."
