name: "Build"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The container image tag.'
        required: true
        default: conexed-io
      build-project:
        description: 'Build the container image?'
        required: true
        default: "yes"
      build-ami:
        description: 'Build the AMI?'
        required: true
        default: "yes"
      deploy-project:
        description: 'Deploy?'
        required: true
        default: "yes"

jobs:
  Build:
    if: ${{ github.event.inputs.build-project == 'yes' }}

    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        run: echo "Building Project"

  Build_AMI:
    if: ${{ github.event.inputs.build-ami == 'yes' }}

    needs: Build

    runs-on: ubuntu-latest

    steps:
      - name: Build AMI
        run: echo "Building AMI"

  Deploy:
    if: ${{ github.event.inputs.deploy-project == 'yes' }}

    runs-on: ubuntu-latest

    steps:
      - name: Build AMI
        run: echo "Building AMI"
