name: "1. Build"

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Default Environment
        run: |
          env

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Hello World
        run: |
          ./hello-world.sh
          env
