name: "1. Build"

on:
  push:

if: github.ref == 'main'
env:
  IMAGE_TAG: latest

if: github.ref == 'env1'
env:
  IMAGE_TAG: env1

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Default Environment
        run: env

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Hello World
        run: |
          ./hello-world.sh
          env
