name: "Build Project"

on:
  workflow_call:
    inputs:
      build-project:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        if: ${{ inputs.build-project == 'yes' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG

      - name: Skip project build
        if: ${{ inputs.build-project == 'no' }}
        run: echo "Skip project build."
