name: "Build Project"

on:
  workflow_call:
    inputs:
      build-project:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure QA AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_GITHUB_ACTIONS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_GITHUB_ACTIONS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout Repo
        if: ${{ inputs.build-project == 'yes' }}
        uses: actions/checkout@v2

      - name: Project Workspace
        if: ${{ inputs.build-project == 'yes' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG
          echo ""
          cd $GITHUB_WORKSPACE
          echo "Working directory"
          pwd
          find .
          echo ""
          echo "Test AWS CLI"
          aws ec2 describe-regions

      # - name: Build Project
      #   if: ${{ inputs.build-project == 'yes' }}
      #   uses: ./.github/actions/build
      #   with:
      #     aws-access-key-id: ${{ secrets.QA_GITHUB_ACTIONS_AWS_ACCESS_KEY_ID }}
      #     aws-region: "us-west-2"
      #     aws-secret-access-key: ${{ secrets.QA_GITHUB_ACTIONS_AWS_SECRET_ACCESS_KEY }}

      - name: Skip project build
        if: ${{ inputs.build-project == 'no' }}
        run: echo "Skip project build."
