name: "Project"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Project Workspace
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG
          echo ""
          cd $GITHUB_WORKSPACE
          echo "Working directory"
          pwd
          find .

      - name: Build Project
        uses: ./.github/actions/build
