name: "Build Project"

on:
  workflow_call:
    inputs:
      build-project:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build:
    if: ${{ inputs.build-project == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Project Workspace
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG
          echo ""
          cd $GITHUB_WORKSPACE
          echo "Working directory"
          pwd
          find .

      - name: Build Project
        uses: ./.github/actions/build

  Skip_Build:
    if: ${{ inputs.build-project == 'no' }}
    runs-on: ubuntu-latest

    steps:
      - name: Skip Build
        run: echo "Skip project build."
