name: "Build"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      build-project:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        if: ${{ inputs.build-project == 'yes' }}
        run: echo "Building Project: "${{ inputs.tag }}

      - name: Skip project build
        if: ${{ inputs.build-project == 'no' }}
        run: echo "Skip project build."
