name: "Build Project"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG
