name: "Build AMI"

on:
  workflow_call:
    inputs:
      build-ami:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  Build_AMI:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build AMI
        if: ${{ inputs.build-ami == 'yes' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "Building AMI"
          echo "- Environment:" $ENVIRONMENT
          echo "- Image Tag:" $TAG

      - name: Skip AMI Build
        if: ${{ inputs.build-ami == 'no' }}
        run: echo "Skip AMI Build"
