name: "Deploy"

on:
  workflow_call:
    inputs:
      deploy-project:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Prod
        if: ${{ inputs.deploy-project == 'yes' && inputs.environment == 'prod' && github.actor == 'm3ta4' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Deploying Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Triggerd by:" $GITHUB_ACTOR

      - name: Deploy QA
        if: ${{ inputs.deploy-project == 'yes' && inputs.environment == ( 'test' || 'io' ) }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Deploying Project"
          echo "- Environment:" $ENVIRONMENT

      - name: Skip Deploy
        if: ${{ inputs.deploy-project == 'no' }}
        run: echo "Skip deploy."
