name: "Deploy"

on:
  workflow_call:
    inputs:
      build-ami:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        if: ${{ inputs.deploy-project == 'yes' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Deploying Project"
          echo "- Environment:" $ENVIRONMENT

      - name: Skip project build
        if: ${{ inputs.build-project == 'no' }}
        run: echo "Skip deploy."
