name: "Deploy"

on:
  workflow_call:
    inputs:
      deploy-project:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [classrooms, groups]
        aws-region: [
          ap-east-1,
          ap-southeast-1,
          ap-southeast-2,
          ca-central-1,
          eu-west-2,
          me-south-1,
          us-east-1,
          us-east-2,
          us-west-1,
          us-west-2
        ]
      exclude:
        - service: groups
          aws-region: [
            ap-east-1,
            ap-southeast-1,
            ap-southeast-2,
            ca-central-1,
            eu-west-2,
            me-south-1
          ]

    steps:
      - name: Deploy Prod
        if: ${{ inputs.deploy-project == 'yes' && inputs.environment == 'prod' && github.actor == 'm3ta4' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Deploying Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Triggerd by:" $GITHUB_ACTOR

      - name: Deploy QA
        if: ${{ inputs.deploy-project == 'yes' && inputs.environment == ( 'test' || 'io' ) }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          SERVICE: ${{ matrix.service }}
          REGION: ${{ matrix.aws-region }}
        run: |
          echo "Deploying Project"
          echo "- Environment: " $ENVIRONMENT
          echo "- Triggerd by: " $GITHUB_ACTOR
          echo "- Service: " $SERVICE
          echo "- Region: " $REGION
          echo " "
          echo "-----ENVIRONMENT----- "
          env

      - name: Skip Deploy
        if: ${{ inputs.deploy-project == 'no' }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          DEPLOY: ${{ inputs.deploy-project }}
        run: |
          echo "Skip Deploying Project"
          echo "- Environment:" $ENVIRONMENT
          echo "- Triggerd by:" $GITHUB_ACTOR
          echo "- Deploy:" $DEPLOY
