name: Deploy

on:
  workflow_run:
    workflows: ["Test Github Actions"]
    branches: [main]
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy
        run: ./deploy.sh
