name: "2. Deploy"

on:
  workflow_run:
    workflows: ["1. Build"]
    branches: [env1]
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy
        run: ./deploy.sh
