name: "CI/CD"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The ConexED environment to deploy to: test, io or prod.'
        required: true
        default: "test"
      tag:
        description: 'The container image tag.'
        required: true
        default: "latest"
      build-project:
        description: 'Build the container image?'
        required: true
        default: "yes"
      build-ami:
        description: 'Build the AMI?'
        required: true
        default: "yes"
      deploy-project:
        description: 'Deploy?'
        required: true
        default: "yes"

jobs:
  _1:
    uses: m3ta4/github-actions-lab/.github/workflows/build.yml@main
    with:
      build-project: ${{ github.event.inputs.build-project }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}

  _2:
    needs: Build
    uses: m3ta4/github-actions-lab/.github/workflows/build-ami.yml@main
    with:
      build-ami: ${{ github.event.inputs.build-ami }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}

  _3:
    needs: Build_AMI
    uses: m3ta4/github-actions-lab/.github/workflows/deploy.yml@main
    with:
      deploy-project: ${{ github.event.inputs.build-ami }}
      environment: ${{ github.event.inputs.environment }}
