name: "CI/CD"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The ConexED environment to deploy to: test, IO or prod.'
        required: true
        default: "test"
      tag:
        description: 'The container image tag.'
        required: true
        default: "latest"
      build-project:
        description: 'Build the container image?'
        required: true
        default: "yes"
      build-ami:
        description: 'Build the AMI?'
        required: true
        default: "yes"
      deploy-project:
        description: 'Deploy?'
        required: true
        default: "yes"

jobs:
  Build:
    uses: m3ta4/github-actions-lab/.github/workflows/build.yml@main
    with:
      build-project: ${{ github.event.inputs.build-project }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}

  Build_AMI:
    needs: Build
    uses: m3ta4/github-actions-lab/.github/workflows/build-ami.yml@main
    with:
      build-ami: ${{ github.event.inputs.build-ami }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}

  Deploy:
    needs: Build_AMI
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        if: ${{ github.event.inputs.deploy-project == 'yes' }}
        run: echo "Deploy AMI"

      - name: Skip Deploy
        if: ${{ github.event.inputs.deploy-project == 'no' }}
        run: echo "Skip deploy"
